#!/bin/bash

# Version Checker 
version="1.0.9"

source ../version.ini
source ../configuration.ini
source formatting.ini

# Compare Versions
echo -e
echo -e "$YELLOW Checking version with github. $RESET"
if [ $version != $backup ]; then
    echo -e "$YELLOW Script update avaibale! $RESET"
    echo -e "$YELLOW Downloading shell file. $RESET"
    curl https://raw.githubusercontent.com/Zendrex/ARK-Linux-Server-Script/master/.serverscript/backup -o backup -#
    echo -e "$GREEN File overwritten. Please restart the script. $RESET"
    exit 0
else
    echo -e " Up to date!"
    echo -e
fi

echo -e "$GREEN Beginning backup process. $RESET"
echo -e; sleep 2s
echo -e " Checking if there is a backups directory."
cd ../
if [-d backups ]; then
  echo -e "$YELLOW Backups directory already made. Moving forward. $RESET"
  echo -e
else
  echo -e "$ERR The backups directory doesnt exists, making it now. $RESET"
  mkdir backups
  echo -e 
fi

echo -e "$YELLOW Backing up save files now. $RESET"
cp ShooterGame/Saved/SavedArks/ ../../.backup/SavedArks
echo -e "$GREEN Backup complete! $RESET"
exit 0
