#!/bin/bash

# Version Checker 
version="1.0.5"

echo "Checking version with github."

source ../version.ini

# Compare Versions
if [ $version != $backup ]; then
    echo "Script update avaibale!"
    echo "Updating script. Please wait."
    echo "Downloading shell file."
    curl https://raw.githubusercontent.com/Zendrex/ARK-Linux-Server-Script/master/.serverscript/backup -o backup -#
    echo "File overwritten. Restarting script."
    echo
    echo "TODO: MAKESURE THERE IS NO STALL"
    exit 0
fi

source ../configuration.ini
cd ../

echo
echo "Beginning backup process."
echo
sleep 2s
echo "Checking if there is a backups directory."

if [-d .backups ]; then
  echo
  echo "Backups directory already made. Moving forward."
  echo
else
  echo
  echo "The backups directory doesnt exists, making it now."
  mkdir .backups
  echo
fi
echo "Entering save directory."
cd ShooterGame
cd Saved
cp SavedArks/ ../../.backup/SavedArks
echo
echo "Backup complete!"
exit 0
