#!/bin/bash

source ../configuration.ini

cd ../
if [ -d steamcmd ]; then
  echo
  echo "There was a directory already named 'steamcmd', is it ok to delete this?"
  echo
  echo "Type: [Y]es or [N]o"
  echo -n "[Y/N]: " ; read installchoice
fi

if [ $installchoice = Y ]; then
  echo "Deleting directory. Please wait."
  rm -rf steamcmd/
  echo
  echo "Directory deleted, moving foward."
else
  echo
  echo "You either chose No or put a wrong response."
  echo "Directory will not be deleted, script stopping. There is no overried available."
  exit 0
fi

echo
echo "Creating directory 'steamcmd'"
mkdir steamcmd

if [ -d steamcmd ]; then
  echo
  echo "Directory created, moving forward."
  cd steamcmd
else
  echo
  echo "Unable to make the directory, please post this to the issues on github."
  echo "https://github.com/Zendrex/ARK-Linux-Server-Script/issues"
  exit 0
fi

echo
echo "Installing linux steam dependencies."
sudo apt-get install lib32gcc1
echo "Lib32gcc1 is installed."
echo
echo "Downloading steamcmd zip."
curl https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz -o steamcmd_linux.tar.gz -#
echo
echo "Unzipping zip."
tar -xvzf steamcmd_linux.tar.gz
echo
echo "Logging into steamcmd and downlading/installing the game server files. This may take a while."
echo
./steamcmd.sh +login anonymous +force_install_dir ../ +app_update $gameid validate +quit
echo
echo "Complete. Exiting."
echo
echo "Please restart the script to start the server."
