#!/bin/bash

# Version Checker 
version="1.0.7"

echo "Checking version with github."
source ../version.ini

# Compare Versions
if [ $version != $stopserver ]; then
    echo "Script update avaibale!"
    echo "Updating script. Please wait."
    echo "Downloading shell file."
    curl https://raw.githubusercontent.com/Zendrex/ARK-Linux-Server-Script/master/.serverscript/stopserver -o stopserver -#
    echo "File overwritten. Restarting script."
    echo
    echo "TODO: MAKESURE THERE IS NO STALL"
    exit 0
fi

source ../configuration.ini

echo
echo "Prepairing to stop the server."
echo

if screen -list | grep -q "$sessionName"; then
    echo
    echo "Server is running, now stopping it."
    echo
    screen -S $sessionName -X quit
    echo "Session stopped. Removing PID's"
    echo
    pkill -9 $arkExecute
    echo "PID's Removed"
else
  echo
  echo "Could not find the server session. The server is not running."
  echo
  exit 0
fi
