#!/bin/bash

source ../configuration.ini

echo
echo "Prepairing to update the server..."
echo
sleep 1s
echo "Checking to see if the server is on or off."
sleep 2s

# First Live Server Check
if screen -list | grep -q "$sessionName"; then
    echo
    echo "Server is running, now stopping it."
    echo
    screen -S $sessionName -X quit
    echo "Server is now stopping. Giving the server 10 seconds before continuting."
    sleep 10s
else
  echo
  echo "Server isnt running, doing second check before continuing."
fi

# Second Live Server Check
if screen -list | grep -q "$sessionName"; then
    echo
    echo "Server is still online. Seems the script cant stop it."
    echo
    echo "Try to manualy stop it with the following commands:"
    echo
    echo "$ screen -ls"
    echo "$ kill -9 <screen PID>"
    echo
    exit 0
else
  echo
  echo "Second check shows the server is offline. :) Moving foward."
fi

cd ../
