#!/bin/bash

source ../configuration.ini

echo
echo "Checking in session exists..."
if screen -list | grep -q "$sessionName"; then
    echo
    echo -e " \e[1;32mIMPORTANT"
    echo
    echo " To detach from this screen, hold CTRL+A+D (in that order)"
    echo
    echo " You will be brought to the session in 10 seconds."
    sleep 10s
    clear
    screen -r $sessionName
    echo
else
  echo
  echo "Could not find the server session. The server is not running."
  echo
  exit 0
fi
